version: '3'
services:
  postgres:
    image: 'postgres:11'
    restart: always
    environment:
    - PGDATA=/tmp
    - POSTGRES_USERNAME=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_HOST=postgres
    - POSTGRES_PORT=5432
    - POSTGRES_DB=postgres
    ports:
    - "5432:5432"
    volumes:
      - "/Users/tom/reviewsAPI/data/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
      - "/Users/tom/reviewsAPI/data:/var/lib/postgresql/data/csv"
  server :
    build : 
      dockerfile : Dockerfile
      context : ./server
    depends_on : 
      - postgres
    restart: always
    ports :
      - "8901:8901"
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    volumes :
      - ./server:/app
      - /app/node_modules